defmodule StatifierBlocks.Compiler.SerializerTest do
  use ExUnit.Case, async: true

  alias Statifier.Machine.Identity
  alias StatifierBlocks.{Compiler, CoreFixtures, Document, Emission}
  alias StatifierBlocks.Compiler.Serializer

  describe "to_binary/1" do
    # sabotage: change the childless clause to write `<name></name>` ->
    # this assertion goes red (verified)
    test "writes one canonical empty-element form" do
      assert Serializer.to_binary(Emission.element("final", [{"id", "s_x"}])) ==
               ~s(<final id="s_x"/>)
    end

    # sabotage: drop the sort in Emission.element/3's normalize/1 -> the
    # two orderings below produce different bytes and this goes red (verified)
    test "writes attributes in sorted order whatever order they were given in" do
      forward = Emission.element("state", [{"id", "s_x"}, {"initial", "s_y"}])
      backward = Emission.element("state", [{"initial", "s_y"}, {"id", "s_x"}])

      assert Serializer.to_binary(forward) == Serializer.to_binary(backward)
      assert Serializer.to_binary(forward) == ~s(<state id="s_x" initial="s_y"/>)
    end

    # sabotage: drop the `is_nil` rejection from normalize/1 -> a nil-valued
    # attribute is written and this goes red (verified)
    test "drops an attribute whose value is nil rather than writing it empty" do
      assert Serializer.to_binary(Emission.element("state", [{"id", "s_x"}, {"initial", nil}])) ==
               ~s(<state id="s_x"/>)
    end

    # sabotage: remove the `&` replacement from escape/1 -> the ampersand in
    # the cond escapes as `&lt;` only and this goes red (verified)
    test "escapes the five characters that would otherwise change the parse" do
      element = Emission.element("transition", [{"cond", ~s(a < b & c > d & e = "f")}])

      assert Serializer.to_binary(element) ==
               ~s(<transition cond="a &lt; b &amp; c &gt; d &amp; e = &quot;f&quot;"/>)
    end

    # sabotage: make the escape order replace `&` last -> the already-written
    # entities are double-escaped and this round trip goes red (verified)
    test "escaping survives a round trip through the engine's parser" do
      {:ok, document} = Document.from_json(File.read!(worked_example()))
      {:ok, compiled} = Compiler.compile(document, CoreFixtures.palette())

      assert compiled.scxml =~ ~s(cond="score &gt; 80")
      assert {:ok, _machine} = Statifier.compile(compiled.scxml)
    end

    # sabotage: have iodata/1 raise on nothing and return "" for a child
    # placeholder -> this assertion goes red (verified)
    test "refuses to write an unspliced child placeholder into identity-bearing bytes" do
      emission = Emission.element("state", [{"id", "s_x"}], [Emission.child_ref("blk_ORPHAN")])

      assert_raise ArgumentError, ~r/blk_ORPHAN/, fn -> Serializer.to_binary(emission) end
    end
  end

  describe "whitespace sensitivity (ADR-0004 decision 6 / st-ADR-0052)" do
    # This is the regression test ADR-0004 names as unenforced: chart
    # identity hashes source bytes, so the serializer's whitespace is
    # identity-bearing and a "harmless" pretty-printing pass is not harmless.
    #
    # sabotage: make iodata/1 join an element's children with "\n" -> the
    # generated bytes gain whitespace and the first assertion goes red
    # (verified)
    test "the generated SCXML carries no whitespace between elements" do
      scxml = compiled_worked_example().scxml

      refute scxml =~ ~r/>\s+</
      refute scxml =~ "\n"
    end

    # sabotage: have iodata/1 write a newline after every open tag -> the
    # serializer's own output is already the reformatted spelling, the two
    # hashes agree, and this goes red (verified). *Which* bytes the
    # identity is taken over is asserted separately in compiler_test.exs,
    # against the engine's own hash of the same bytes.
    test "a whitespace-only reformat changes chart identity" do
      compiled = compiled_worked_example()
      reformatted = String.replace(compiled.scxml, "><", ">\n  <")

      refute Identity.matches?(
               compiled.record.chart_identity,
               Identity.of_source(reformatted, chart_name: compiled.record.document_id)
             )
    end

    # The other half of the same fact, and the reason it matters: the
    # reformatted chart is the *same chart* to the engine and a *different
    # chart* to identity, so st-ADR-0060's resume would refuse a session
    # started against the other spelling.
    #
    # sabotage: as above -> this assertion pair no longer demonstrates the
    # split and the refute goes red (verified)
    test "the reformatted bytes still compile, which is what makes the drift silent" do
      compiled = compiled_worked_example()
      reformatted = String.replace(compiled.scxml, "><", ">\n  <")

      assert {:ok, machine} =
               Statifier.compile(reformatted, chart_name: compiled.record.document_id)

      refute Identity.matches?(
               Statifier.Machine.identity(machine),
               compiled.record.chart_identity
             )
    end
  end

  defp compiled_worked_example do
    {:ok, document} = Document.from_json(File.read!(worked_example()))
    {:ok, compiled} = Compiler.compile(document, CoreFixtures.palette())
    compiled
  end

  defp worked_example, do: "test/fixtures/documents/worked_example.json"
end
