defmodule StatifierBlocks.MapFixtures do
  @moduledoc """
  The two teaching documents the Map is read against - a library loan and a
  patron registration, one library world - and the words a host of that
  world has for its event names.

  The documents are copies of the reference host's
  (`statifier_examples@c620756`, `priv/fixtures/`), written from `core.*`
  blocks alone, under `test/fixtures/documents/statifier_examples_c620756/`.
  The graphs under `test/fixtures/map/` are what the reference host's own
  map module answered for them at that commit, with the phrase table below
  standing in for the host's: generated by compiling that module against
  this package, never written by hand, so `StatifierBlocks.MapTest` holding
  the package's graph equal to them is the claim that the Map moved without
  changing what it answers.
  """

  alias StatifierBlocks.{Decode, Document, Palette, ViewModel}

  @documents Path.join([__DIR__, "..", "fixtures", "documents", "statifier_examples_c620756"])
  @graphs Path.join([__DIR__, "..", "fixtures", "map"])
  @keys ["library_loan", "patron_registration"]

  # The reference host's table at the same commit, word for word.
  @phrases %{
    "copy.returned" => "the copy is returned",
    "copy.reported_lost" => "the copy is reported lost",
    "loan.closed" => "the loan is closed",
    "loan.renewed" => "the loan is renewed",
    "loan.overdue" => "the loan is overdue",
    "email.verified" => "the email address is verified",
    "guardian.consented" => "a guardian consents",
    "card.ready" => "the card is ready",
    "patron.asked_to_visit" => "the patron is asked to visit",
    "patron.welcomed" => "the patron is welcomed",
    "registration.abandoned" => "the registration is abandoned",
    "registration.deadline" => "the registration week is up"
  }

  @doc "The two teaching documents' keys, in the order a page offers them."
  @spec keys() :: [String.t()]
  def keys, do: @keys

  @doc "The teaching document `key`, strictly decoded."
  @spec document!(String.t()) :: Document.t()
  def document!(key) when key in @keys do
    {:ok, document} = Decode.decode(File.read!(Path.join(@documents, "#{key}.json")))
    document
  end

  @doc "The view model of the teaching document `key`, under the core palette."
  @spec view_model!(String.t()) :: ViewModel.t()
  def view_model!(key), do: key |> document!() |> ViewModel.build(Palette.core(), [])

  @doc "The graph the reference host's map module answered for `key`."
  @spec host_graph!(String.t()) :: map()
  def host_graph!(key) when key in @keys,
    do: JSON.decode!(File.read!(Path.join(@graphs, "#{key}.graph.json")))

  @doc "The library world's words for `event`, or `nil`."
  @spec phrase(String.t()) :: String.t() | nil
  def phrase(event) when is_binary(event), do: Map.get(@phrases, event)
end
