defmodule StatifierBlocks.ProvenanceTest do
  @moduledoc """
  The map itself (ADR-0004 decision 5), away from the compiler that fills
  it: innermost-span routing, the state-id key, and the canonical
  serialization a host stores beside the SCXML.
  """

  use ExUnit.Case, async: true

  alias StatifierBlocks.Provenance

  # A block's state, a transition inside it, and one attribute value inside
  # that transition - the three nesting depths a real emission produces.
  defp nested do
    outer = Provenance.owner("blk_SEQ")
    inner = Provenance.owner("blk_STEP", role: "pick")
    field = Provenance.owner("blk_STEP", role: "pick", config_key: "arm_paid")

    %Provenance{
      by_state_id: %{"s_blk_SEQ" => outer, "s_blk_STEP__pick" => inner},
      spans: [{{0, 100}, outer}, {{20, 60}, inner}, {{30, 40}, field}]
    }
  end

  describe "owner_at/2" do
    # Sabotage: made `owner_at/2` take `Enum.max_by(&width/1)` instead of
    # `min_by` - red on both of the inner assertions, which is the
    # innermost rule earning its keep.
    test "the innermost span containing the offset wins" do
      map = nested()

      assert {:ok, %{block_id: "blk_SEQ", role: nil, config_key: nil}} =
               Provenance.owner_at(map, 5)

      assert {:ok, %{block_id: "blk_STEP", role: "pick", config_key: nil}} =
               Provenance.owner_at(map, 25)

      assert {:ok, %{block_id: "blk_STEP", role: "pick", config_key: "arm_paid"}} =
               Provenance.owner_at(map, 35)
    end

    # Sabotage: changed the end-offset test from `offset < stop` to
    # `offset <= stop` - red, because offset 100 then resolves instead of
    # coming back unmapped.
    test "the end offset is exclusive, as upstream's locations are" do
      map = nested()

      assert {:ok, %{block_id: "blk_SEQ"}} = Provenance.owner_at(map, 99)
      assert Provenance.owner_at(map, 100) == {:error, {:unmapped_offset, 100}}
    end

    # Sabotage: made the empty-candidates arm return `{:ok, hd(spans)}` -
    # red, because an offset from another chart then resolves to a block
    # that has nothing to do with it.
    test "an offset outside the generated bytes is unmapped rather than guessed" do
      assert Provenance.owner_at(%Provenance{}, 7) == {:error, {:unmapped_offset, 7}}
    end
  end

  describe "owner_of_state/2 and owners_of_states/2" do
    # Sabotage: made `owner_of_state/2` fall back to the first span's
    # owner - red on the `:error` assertion.
    test "a generated state resolves and an unknown one does not" do
      map = nested()

      assert {:ok, %{block_id: "blk_SEQ"}} = Provenance.owner_of_state(map, "s_blk_SEQ")
      assert Provenance.owner_of_state(map, "s_blk_ELSEWHERE") == :error
    end

    # Sabotage: made `owners_of_states/2` sort its result - red, because a
    # highlighting caller relies on the configuration's own order.
    test "a running configuration maps in order, dropping states from another chart" do
      owners =
        Provenance.owners_of_states(nested(), [
          "s_blk_STEP__pick",
          "s_blk_ELSEWHERE",
          "s_blk_SEQ"
        ])

      assert [%{block_id: "blk_STEP"}, %{block_id: "blk_SEQ"}] = owners
    end
  end

  describe "to_json/1 and from_json/1" do
    # Sabotage: dropped the `Enum.sort_by/2` from `CanonicalJson.object/1`
    # - red, because the two encodings then differ by key order.
    test "the encoding is canonical: sorted keys and no insignificant whitespace" do
      json = Provenance.to_json(nested())

      refute json =~ " "
      assert json =~ ~s("by_state_id")

      assert String.contains?(
               json,
               ~s({"block_id":"blk_STEP","config_key":"arm_paid","role":"pick"})
             )
    end

    # Sabotage: made `owner_term/1` write `"role":null` instead of
    # omitting an absent role - red, because the round trip then reads
    # back a map that is `==` but whose bytes are not the shorter form
    # this assertion pins.
    test "a nil role and a nil config key are omitted, not written as null" do
      json = Provenance.to_json(nested())

      refute json =~ "null"
      assert json =~ ~s({"block_id":"blk_SEQ"})
    end

    # Sabotage: swapped `"start"` and `"end"` in `from_term/1` - red on the
    # round-trip equality.
    test "what to_json/1 writes, from_json/1 reads back unchanged" do
      map = nested()

      assert {:ok, decoded} = map |> Provenance.to_json() |> Provenance.from_json()
      assert decoded == map
      assert Provenance.to_json(decoded) == Provenance.to_json(map)
    end

    # Sabotage: removed the `from_term/1` fallback clause - red with a
    # FunctionClauseError instead of the error tuple, which is the
    # totality this package promises everywhere else.
    test "malformed input is an error tuple rather than a raise" do
      assert {:error, _reason} = Provenance.from_json("not json at all")
      assert {:error, {:not_a_provenance_map, _term}} = Provenance.from_json(~s({"nope":1}))
    end
  end
end
