defmodule StatifierBlocks.Compiler do
  @moduledoc """
  The one-way compile: a block document plus a palette in, one artifact out
  (ADR-0004 decisions 1-4, 6-7).

  `compile/3` is a **total function of `{document, palette}`**. No process
  state, no global registry, no IO, no clock - the same purity ADR-0002
  decision 4 imposes on the callbacks, imposed on the pipeline that calls
  them. It returns `{:ok, %StatifierBlocks.Compiled{}}` or
  `{:error, [%StatifierBlocks.Compiler.Finding{}]}`, never raises, and never
  partially succeeds.

  ## The pipeline

  Each stage runs over the whole document; the first stage that produces
  errors stops the compile and reports every error it found. Stopping
  rather than accumulating across stages is deliberate - see
  `StatifierBlocks.Compiler.Finding`.

  1. **Document** - `StatifierBlocks.Document.validate/1`. Structural only;
     no palette is consulted.
  2. **Resolve** - every block through
     `StatifierBlocks.Palette.resolve/2`, which also applies an in-memory
     config migration (ADR-0002 decision 8). Nothing is written back.
  3. **Config** - every block's `validate_config/1`.
  4. **Emit** - bottom-up. Each block's `emit/2` is called with its
     children already compiled and summarized, and its child placeholders
     are spliced with those children's own emissions.
  5. **Serialize** - once, at the end, through
     `StatifierBlocks.Compiler.Serializer`, then
     `Statifier.Machine.Identity.of_source/2` over the bytes just written.

  The `Structure` stage decision 10 names - slot arity, `:undeclared_slot`,
  assignability - is **not** in this list. `sb-da9` owns the first two and
  `sb-b3t` shipped `StatifierBlocks.Assignability.validate/3` for the
  third; wiring them in as a stage between Config and Emit is sb-qz0's,
  alongside the rest of decision 10. Until then this pipeline simply never
  visits a slot `slots/1` did not declare, so an undeclared slot's blocks
  are absent from the emission rather than misplaced in it.

  ## Determinism (decision 6)

  > For a fixed `{document canonical bytes, palette, compiler version}`, the
  > generated SCXML is **byte-identical** on every machine and every run,
  > forever.

  All three inputs are real, and `StatifierBlocks.CompilationRecord`
  records all three. What this module contributes to the guarantee is that
  it never iterates a bare map: slots are visited in `slots/1` declaration
  order (ADR-0002 decision 6 made that order meaningful), children in
  document order, and attributes are sorted at construction by
  `StatifierBlocks.Emission.element/3`.

  The guarantee is **not** reversible and must not be read as one. Equal
  output does not imply equal input: a `metadata`-only edit changes the
  document hash and produces identical SCXML, because `metadata` is not
  compiled. A host may use "same triple" to skip a recompile, and may
  **not** use "same SCXML" to conclude the document is unchanged.
  """

  alias Statifier.Machine.Identity

  alias StatifierBlocks.{
    Block,
    CompilationRecord,
    Compiled,
    Document,
    Emission,
    Palette
  }

  alias StatifierBlocks.Compiler.{Context, Finding, Serializer, StateId}

  @scxml_ns "http://www.w3.org/2005/07/scxml"

  # Decision 6's third determinism input. It is the package version, and it
  # moves whenever a change to this package moves generated bytes - which,
  # since a Hex release is the only way a host's bytes change, is every
  # release. `compiler_version_test.exs` asserts it against `mix.exs` so the
  # two cannot drift silently.
  @compiler_version "0.1.0"

  # A resolved block and its resolved children, in `slots/1` declaration
  # order. Built once by the Resolve stage and threaded through the rest, so
  # no later stage re-resolves or re-migrates anything.
  defmodule Resolved do
    @moduledoc false

    @type t :: %__MODULE__{
            block: StatifierBlocks.Block.t(),
            module: module(),
            slots: [{StatifierBlocks.Block.slot_name(), [t()]}]
          }

    @enforce_keys [:block, :module, :slots]
    defstruct [:block, :module, :slots]
  end

  @doc """
  Compiles `document` against `palette`.

  `opts` is accepted and currently unread. Decision 8's
  `:known_invoke_types` lint lands with sb-qz0; taking the option now keeps
  that a behaviour change rather than an arity change at every call site.
  """
  @spec compile(Document.t(), Palette.t(), keyword()) ::
          {:ok, Compiled.t()} | {:error, [Finding.t()]}
  def compile(%Document{} = document, %Palette{} = palette, opts \\ []) when is_list(opts) do
    with :ok <- document_stage(document),
         {:ok, node} <- resolve_stage(document, palette),
         :ok <- config_stage(node),
         {:ok, emission} <- emit_stage(node, document.id) do
      {:ok, artifact(document, node, emission)}
    end
  end

  @doc "Decision 6's third determinism input: this package's version."
  @spec compiler_version() :: String.t()
  def compiler_version, do: @compiler_version

  # -- Stage 1: document -----------------------------------------------------

  @spec document_stage(Document.t()) :: :ok | {:error, [Finding.t()]}
  defp document_stage(document) do
    case Document.validate(document) do
      :ok ->
        :ok

      {:error, reason} ->
        {:error,
         [
           Finding.new(
             :document,
             {:invalid_document, reason},
             "the document is not structurally valid: #{inspect(reason)}"
           )
         ]}
    end
  end

  # -- Stage 2: resolve ------------------------------------------------------

  @spec resolve_stage(Document.t(), Palette.t()) :: {:ok, Resolved.t()} | {:error, [Finding.t()]}
  defp resolve_stage(%Document{root: root}, palette) do
    case resolve(palette, root) do
      {:ok, node} -> {:ok, node}
      {:error, findings} -> {:error, findings}
    end
  end

  @spec resolve(Palette.t(), Block.t()) :: {:ok, Resolved.t()} | {:error, [Finding.t()]}
  defp resolve(palette, %Block{} = block) do
    case Palette.resolve(palette, block) do
      {:ok, module, resolved} ->
        resolve_children(palette, module, resolved)

      {:error, reason} ->
        {:error, [resolve_finding(block, reason) | orphan_findings(palette, block)]}
    end
  end

  @spec resolve_children(Palette.t(), module(), Block.t()) ::
          {:ok, Resolved.t()} | {:error, [Finding.t()]}
  defp resolve_children(palette, module, %Block{} = block) do
    {slots, findings} =
      block.config
      |> module.slots()
      |> Enum.reduce({[], []}, fn {name, _arity, _label}, {slots, findings} ->
        {children, child_findings} = resolve_slot(palette, block, name)
        {[{name, children} | slots], findings ++ child_findings}
      end)

    case findings do
      [] -> {:ok, %Resolved{block: block, module: module, slots: Enum.reverse(slots)}}
      findings -> {:error, findings}
    end
  end

  @spec resolve_slot(Palette.t(), Block.t(), Block.slot_name()) :: {[Resolved.t()], [Finding.t()]}
  defp resolve_slot(palette, %Block{slots: slots}, name) do
    slots
    |> Map.get(name, [])
    |> Enum.reduce({[], []}, fn child, {nodes, findings} ->
      case resolve(palette, child) do
        {:ok, node} -> {[node | nodes], findings}
        {:error, child_findings} -> {nodes, findings ++ child_findings}
      end
    end)
    |> then(fn {nodes, findings} -> {Enum.reverse(nodes), findings} end)
  end

  # A block whose own type did not resolve has no `slots/1` to walk, so its
  # children are visited in sorted slot-name order instead. Reporting them
  # too is decision 10's "within a stage every finding is reported": the
  # children's types are siblings of this failure, not consequences of it.
  @spec orphan_findings(Palette.t(), Block.t()) :: [Finding.t()]
  defp orphan_findings(palette, %Block{slots: slots}) do
    slots
    |> Enum.sort_by(&elem(&1, 0))
    |> Enum.flat_map(fn {_name, children} -> children end)
    |> Enum.flat_map(&orphan_child_findings(palette, &1))
  end

  @spec orphan_child_findings(Palette.t(), Block.t()) :: [Finding.t()]
  defp orphan_child_findings(palette, child) do
    case resolve(palette, child) do
      {:ok, _node} -> []
      {:error, findings} -> findings
    end
  end

  @spec resolve_finding(Block.t(), term()) :: Finding.t()
  defp resolve_finding(%Block{id: id, type: type}, {:unknown_block_type, _type} = reason) do
    Finding.new(:resolve, reason, ~s(no palette entry for block type "#{type}"), block_id: id)
  end

  defp resolve_finding(%Block{id: id}, {:block_type_too_new, _id, stored} = reason) do
    Finding.new(
      :resolve,
      reason,
      "the block is stored at type version #{stored}, which is newer than this palette entry",
      block_id: id
    )
  end

  defp resolve_finding(%Block{id: id}, {:migration_failed, _id, why} = reason) do
    Finding.new(:resolve, reason, "config migration failed: #{inspect(why)}", block_id: id)
  end

  # -- Stage 3: config -------------------------------------------------------

  @spec config_stage(Resolved.t()) :: :ok | {:error, [Finding.t()]}
  defp config_stage(node) do
    case config_findings(node) do
      [] -> :ok
      findings -> {:error, findings}
    end
  end

  @spec config_findings(Resolved.t()) :: [Finding.t()]
  defp config_findings(%Resolved{block: block, module: module, slots: slots}) do
    own =
      case module.validate_config(block.config) do
        :ok ->
          []

        {:error, findings} ->
          Enum.map(findings, fn {key, message} ->
            Finding.new(:config, {:invalid_config, key}, message,
              block_id: block.id,
              config_key: key
            )
          end)
      end

    own ++
      Enum.flat_map(slots, fn {_name, children} -> Enum.flat_map(children, &config_findings/1) end)
  end

  # -- Stage 4: emit ---------------------------------------------------------

  @spec emit_stage(Resolved.t(), Document.id()) :: {:ok, Emission.t()} | {:error, [Finding.t()]}
  defp emit_stage(node, document_id) do
    with {:ok, emission} <- emit(node, document_id) do
      {:ok, scxml_element(node, document_id, emission)}
    end
  end

  @spec emit(Resolved.t(), Document.id()) :: {:ok, Emission.t()} | {:error, [Finding.t()]}
  defp emit(%Resolved{block: block, module: module, slots: slots}, document_id) do
    with {:ok, compiled_slots} <- emit_slots(slots, document_id) do
      context = Context.new(block.id, document_id, summaries(compiled_slots))

      case module.emit(block, context) do
        {:ok, %Emission{} = emission} -> splice(emission, compiled_slots, block)
        {:error, reason} -> {:error, emit_findings(block, reason)}
      end
    end
  end

  @spec emit_slots([{Block.slot_name(), [Resolved.t()]}], Document.id()) ::
          {:ok, [{Block.slot_name(), [{Block.id(), Emission.t()}]}]} | {:error, [Finding.t()]}
  defp emit_slots(slots, document_id) do
    Enum.reduce_while(slots, {:ok, []}, fn {name, children}, {:ok, acc} ->
      case emit_children(children, document_id) do
        {:ok, compiled} -> {:cont, {:ok, [{name, compiled} | acc]}}
        {:error, findings} -> {:halt, {:error, findings}}
      end
    end)
    |> case do
      {:ok, acc} -> {:ok, Enum.reverse(acc)}
      {:error, findings} -> {:error, findings}
    end
  end

  @spec emit_children([Resolved.t()], Document.id()) ::
          {:ok, [{Block.id(), Emission.t()}]} | {:error, [Finding.t()]}
  defp emit_children(children, document_id) do
    Enum.reduce_while(children, {:ok, []}, fn %Resolved{block: block} = child, {:ok, acc} ->
      case emit(child, document_id) do
        {:ok, emission} -> {:cont, {:ok, [{block.id, emission} | acc]}}
        {:error, findings} -> {:halt, {:error, findings}}
      end
    end)
    |> case do
      {:ok, acc} -> {:ok, Enum.reverse(acc)}
      {:error, findings} -> {:error, findings}
    end
  end

  @spec summaries([{Block.slot_name(), [{Block.id(), Emission.t()}]}]) ::
          %{optional(Block.slot_name()) => [Context.child_summary()]}
  defp summaries(compiled_slots) do
    Map.new(compiled_slots, fn {name, children} ->
      {name, Enum.map(children, fn {block_id, _emission} -> Context.summary(block_id) end)}
    end)
  end

  # Replaces every `{:child, block_id}` placeholder with that child's own
  # emission. A placeholder naming a block that is not a child of this one in
  # a declared slot is a bug in the block type, reported against the parent
  # rather than written into identity-bearing bytes as a hole.
  @spec splice(Emission.t(), [{Block.slot_name(), [{Block.id(), Emission.t()}]}], Block.t()) ::
          {:ok, Emission.t()} | {:error, [Finding.t()]}
  defp splice(emission, compiled_slots, block) do
    available =
      Map.new(Enum.flat_map(compiled_slots, fn {_name, children} -> children end))

    case substitute(emission, available) do
      {:ok, spliced} ->
        {:ok, spliced}

      {:error, block_id} ->
        {:error,
         [
           Finding.new(
             :emit,
             {:unspliced_child, block_id},
             "emitted a child placeholder for #{block_id}, which is not a child of this block",
             block_id: block.id
           )
         ]}
    end
  end

  @spec substitute(Emission.node_t(), %{optional(Block.id()) => Emission.t()}) ::
          {:ok, Emission.t()} | {:error, Block.id()}
  defp substitute(%Emission{children: children} = emission, available) do
    children
    |> Enum.reduce_while({:ok, []}, fn child, {:ok, acc} ->
      case substitute(child, available) do
        {:ok, substituted} -> {:cont, {:ok, [substituted | acc]}}
        {:error, block_id} -> {:halt, {:error, block_id}}
      end
    end)
    |> case do
      {:ok, acc} -> {:ok, %{emission | children: Enum.reverse(acc)}}
      {:error, block_id} -> {:error, block_id}
    end
  end

  defp substitute({:child, block_id}, available) do
    case Map.fetch(available, block_id) do
      {:ok, emission} -> {:ok, emission}
      :error -> {:error, block_id}
    end
  end

  @spec emit_findings(Block.t(), term()) :: [Finding.t()]
  defp emit_findings(%Block{id: id}, {:invalid_role, _block_id, role} = reason) do
    [
      Finding.new(
        :emit,
        reason,
        ~s(minted the state role "#{role}", which is not a lowercase identifier free of "__"),
        block_id: id
      )
    ]
  end

  defp emit_findings(%Block{id: id}, findings) when is_list(findings) do
    Enum.map(findings, fn
      {key, message} when is_binary(key) and is_binary(message) ->
        Finding.new(:emit, {:emit_refused, key}, message, block_id: id, config_key: key)

      other ->
        Finding.new(:emit, {:emit_refused, other}, inspect(other), block_id: id)
    end)
  end

  defp emit_findings(%Block{id: id}, reason) do
    [Finding.new(:emit, {:emit_refused, reason}, inspect(reason), block_id: id)]
  end

  # -- Stage 5: serialize and record ----------------------------------------

  @spec scxml_element(Resolved.t(), Document.id(), Emission.t()) :: Emission.t()
  defp scxml_element(%Resolved{block: %Block{id: root_id}}, document_id, root_emission) do
    Emission.element(
      "scxml",
      [
        {"initial", StateId.state_id(root_id)},
        {"name", document_id},
        {"version", "1.0"},
        {"xmlns", @scxml_ns}
      ],
      [root_emission]
    )
  end

  @spec artifact(Document.t(), Resolved.t(), Emission.t()) :: Compiled.t()
  defp artifact(%Document{} = document, node, emission) do
    scxml = Serializer.to_binary(emission)

    record = %CompilationRecord{
      document_id: document.id,
      revision: document.revision,
      document_hash: Document.content_hash(document),
      palette_hash: palette_hash(node),
      compiler_version: @compiler_version,
      chart_identity: Identity.of_source(scxml, chart_name: document.id, chart_version: nil)
    }

    %Compiled{scxml: scxml, record: record}
  end

  # A digest over the sorted `{type_name, module, current_version}` triples
  # of the entries this compile actually resolved. See
  # `StatifierBlocks.CompilationRecord` for what it does and does not claim.
  @spec palette_hash(Resolved.t()) :: binary()
  defp palette_hash(node) do
    digest =
      node
      |> entries()
      |> Enum.uniq()
      |> Enum.sort()
      |> Enum.map_join("\n", fn {type, module, version} ->
        "#{type}\t#{inspect(module)}\t#{version}"
      end)

    "sha256:" <> Base.encode16(:crypto.hash(:sha256, digest), case: :lower)
  end

  @spec entries(Resolved.t()) :: [{Block.type_name(), module(), pos_integer()}]
  defp entries(%Resolved{block: block, module: module, slots: slots}) do
    [
      {block.type, module, module.current_version()}
      | Enum.flat_map(slots, fn {_name, children} -> Enum.flat_map(children, &entries/1) end)
    ]
  end
end
