defmodule StatifierBlocks.Provenance do
  @moduledoc """
  Which generated element came from which block (ADR-0004 decision 5).

  The compile runs one way and nothing decompiles a chart back into
  blocks. What has to survive the trip is *correspondence*, and this is it.

  ## Keyed two ways, because it answers two different questions

  *Runtime highlighting* starts from a running session, whose active
  configuration is a list of **state ids**
  (`Statifier.active_leaf_states/1`). That is `by_state_id`, and
  `StatifierBlocks.Compiler.StateId`'s totality is what makes it complete.

  *Error routing* starts from an upstream finding, and upstream findings
  carry no element reference at all: every diagnostic in statifier's
  pipeline is `{reason, message, location}` where `location` is a
  `%Statifier.Parser.Location{}`, and the offending ids ride *inside* the
  closed `reason` tuple as data. So the second key is a **byte span over
  the generated SCXML**, and mapping a finding is `owner_at/2` on
  `location.start_offset`.

  A span key is strictly more general than an id-based one. It routes
  findings about transitions, which have no id of their own in SCXML, and
  findings whose reason tuple carries no id at all - and because the
  compiler records the span of every attribute *value* as well as every
  element, it routes a bad expression to the config field the author typed
  it into.

  ## The map is total over the emission

  Every span the compiler emits has an owner; there is no unowned
  scaffolding. Chart-level elements belonging to no particular block - the
  `<scxml>` element itself - are attributed to the **root block**, which
  ADR-0001 decision 1 guarantees exists. Totality is what makes decision
  9's mapping a total function rather than one with an `:unmapped` arm
  every consumer must handle and none can act on. An unmapped offset
  inside the generated bytes is a compiler bug, and `owner_at/2` still
  returns an error tuple for it rather than raising, because a caller may
  hand it an offset from a *different* chart.

  ## Serialization

  `to_json/1` writes the map under ADR-0001 decision 8's canonical rules,
  so a host can store it beside the SCXML, diff it, and read it from
  non-Elixir tooling. It is not part of the document and carries no
  `schema_version` of its own; it is versioned by the compilation record's
  compiler version.
  """

  alias StatifierBlocks.{Block, CanonicalJson}

  @typedoc "Byte offsets into the generated SCXML. Exclusive end, as upstream."
  @type span :: {start_offset :: non_neg_integer(), end_offset :: non_neg_integer()}

  @typedoc """
  `role` is `nil` for the block's own state and a role name for one it
  minted (ADR-0004 decision 3). `config_key` is set when the span was
  emitted verbatim from that config field, which is what makes a finding
  the author's rather than a bug in this package.
  """
  @type owner :: %{
          block_id: Block.id(),
          role: String.t() | nil,
          config_key: String.t() | nil
        }

  @type t :: %__MODULE__{
          by_state_id: %{optional(String.t()) => owner()},
          spans: [{span(), owner()}]
        }

  defstruct by_state_id: %{}, spans: []

  @doc """
  Builds an owner. `opts` carries `:role` and `:config_key`, both `nil` by
  default.
  """
  @spec owner(Block.id(), keyword()) :: owner()
  def owner(block_id, opts \\ []) when is_binary(block_id) do
    %{
      block_id: block_id,
      role: Keyword.get(opts, :role),
      config_key: Keyword.get(opts, :config_key)
    }
  end

  @doc """
  The owner of the innermost span containing `offset`.

  Innermost is by width: spans nest, so the narrowest span containing an
  offset is unique, and an attribute value's span is always strictly
  inside its element's.
  """
  @spec owner_at(t(), non_neg_integer()) ::
          {:ok, owner()} | {:error, {:unmapped_offset, non_neg_integer()}}
  def owner_at(%__MODULE__{spans: spans}, offset) when is_integer(offset) and offset >= 0 do
    spans
    |> Enum.filter(fn {{start, stop}, _owner} -> offset >= start and offset < stop end)
    |> case do
      [] -> {:error, {:unmapped_offset, offset}}
      containing -> {:ok, containing |> Enum.min_by(&width/1) |> elem(1)}
    end
  end

  @doc """
  The owner of the generated state `state_id`, for mapping a running
  session's `Statifier.active_leaf_states/1` back onto blocks.
  """
  @spec owner_of_state(t(), String.t()) :: {:ok, owner()} | :error
  def owner_of_state(%__MODULE__{by_state_id: by_state_id}, state_id) do
    Map.fetch(by_state_id, state_id)
  end

  @doc """
  The blocks a running configuration is inside, in the order the
  configuration was given, with any state this map does not know dropped.

  The drop is deliberate rather than lenient: a state id this map has
  never heard of is a state from a *different* chart, and a highlighting
  caller wants the blocks it can highlight rather than an error over the
  whole list.
  """
  @spec owners_of_states(t(), [String.t()]) :: [owner()]
  def owners_of_states(%__MODULE__{} = provenance, state_ids) when is_list(state_ids) do
    for state_id <- state_ids, {:ok, owner} <- [owner_of_state(provenance, state_id)], do: owner
  end

  @doc "Canonical JSON, ADR-0001 decision 8's rules. Deterministic."
  @spec to_json(t()) :: binary()
  def to_json(%__MODULE__{} = provenance) do
    provenance
    |> to_term()
    |> CanonicalJson.encode_term()
    |> IO.iodata_to_binary()
  end

  @doc "Reads back what `to_json/1` wrote."
  @spec from_json(binary()) :: {:ok, t()} | {:error, term()}
  def from_json(json) when is_binary(json) do
    with {:ok, decoded} <- decode(json) do
      from_term(decoded)
    end
  end

  @spec to_term(t()) :: map()
  defp to_term(%__MODULE__{by_state_id: by_state_id, spans: spans}) do
    %{
      "by_state_id" => Map.new(by_state_id, fn {id, owner} -> {id, owner_term(owner)} end),
      "spans" =>
        Enum.map(spans, fn {{start, stop}, owner} ->
          %{"start" => start, "end" => stop, "owner" => owner_term(owner)}
        end)
    }
  end

  @spec owner_term(owner()) :: map()
  defp owner_term(%{block_id: block_id, role: role, config_key: config_key}) do
    %{"block_id" => block_id}
    |> maybe_put("role", role)
    |> maybe_put("config_key", config_key)
  end

  defp maybe_put(map, _key, nil), do: map
  defp maybe_put(map, key, value), do: Map.put(map, key, value)

  @spec decode(binary()) :: {:ok, term()} | {:error, term()}
  defp decode(json) do
    {:ok, JSON.decode!(json)}
  rescue
    error -> {:error, error}
  end

  @spec from_term(term()) :: {:ok, t()} | {:error, term()}
  defp from_term(%{"by_state_id" => by_state_id, "spans" => spans})
       when is_map(by_state_id) and is_list(spans) do
    {:ok,
     %__MODULE__{
       by_state_id: Map.new(by_state_id, fn {id, owner} -> {id, owner_from_term(owner)} end),
       spans:
         Enum.map(spans, fn %{"start" => start, "end" => stop, "owner" => owner} ->
           {{start, stop}, owner_from_term(owner)}
         end)
     }}
  rescue
    error -> {:error, error}
  end

  defp from_term(other), do: {:error, {:not_a_provenance_map, other}}

  @spec owner_from_term(map()) :: owner()
  defp owner_from_term(%{"block_id" => block_id} = term) do
    owner(block_id, role: Map.get(term, "role"), config_key: Map.get(term, "config_key"))
  end

  @spec width({span(), owner()}) :: non_neg_integer()
  defp width({{start, stop}, _owner}), do: stop - start
end
