defmodule StatifierBlocks.SourceView do
  @moduledoc """
  The generated SCXML as numbered lines of owned spans, for reading.

  ADR-0004 decision 5 keys the provenance map two ways, and this is the
  second key turned around. Error routing asks "which block owns the byte
  this finding points at"; a reader asks the same question of every byte at
  once, and gets back a listing in which each run of bytes carries the block
  that emitted it. Nothing here decompiles anything: the chart is still a
  build product, the document is still the source of truth, and this is a
  read of what one compile produced.

  ## One element per line, because the serializer emits none

  `StatifierBlocks.Compiler.Serializer` writes the whole chart as a single
  line - a chart's bytes are identity-bearing (st-ADR-0052) and whitespace
  the serializer does not need is whitespace that would have to be hashed.
  So the lines here are the reader's, not the file's: a line begins at every
  `<`, which the serializer's own escaping makes an exact rule rather than a
  heuristic (`&`, `<` and `>` are escaped in text and in attribute values,
  so a raw `<` in the output always opens a tag). `indent` is the nesting
  depth the same walk counts, and it is presentation: no byte of the
  generated chart is moved, added or dropped.

  That is the property the whole surface rests on. Concatenating every span
  of every line, in order, reproduces the compiled bytes exactly, which is
  what makes an offset in this listing the same offset
  `StatifierBlocks.Provenance.owner_at/2` was asked about.

  ## A span is one owner's run of bytes

  The cut points are the provenance map's own span endpoints plus the line
  starts, so within one span the innermost owner never changes. The owner is
  read once per span with `owner_at/2` - the *innermost* containing span,
  which is what makes an attribute value's owner its config field rather
  than the element around it - and `config_key` is the field name an author
  typed the value into.

  A span whose `block_id` is `nil` is one no span in the map contains. The
  map is total over the emission, so in practice this is the prologue an
  element span does not reach; it is drawn as plain text rather than
  dropped, because a listing that silently omitted bytes would stop
  reproducing the chart.

  ## Staleness rather than a recompile per keystroke

  A compile is not cheap and this runs off one, so a caller recomputes only
  while something is showing the result - the same discipline
  `StatifierBlocks.Runtime.FixtureRuns` is held to. What that leaves is the
  mid-edit document that does not compile at all. Handing back
  `:compile_error` there would empty the panel on the first half-typed
  expression; handing back the previous listing without saying so would show
  a chart the document no longer produces. So `build/3` takes the previous
  value as `:previous` and, when the new compile fails and the previous one
  succeeded, returns that listing with `stale?` set and the new findings
  beside it. The panel says which document it is looking at, and no
  keystroke recompiles anything.

  ## Unguarded, on purpose

  Like `StatifierBlocks.Runtime.FixtureRuns`, this module names no LiveView
  module and carries no `Code.ensure_loaded?/1` guard: it is a pure function
  of a document and a palette, and the headless suite exercises it directly.
  Drawing it is `StatifierBlocks.Editor.Drawer`'s job.
  """

  alias StatifierBlocks.{Block, Compiled, Compiler, Document, Palette, Provenance}
  alias StatifierBlocks.Compiler.Finding

  defmodule Span do
    @moduledoc """
    One run of generated bytes with one owner, as
    `StatifierBlocks.Provenance.owner_at/2` answers for it.

    `offset` is the byte offset the run starts at, which is the offset that
    was resolved. `block_id` is `nil` for a run no span in the map contains.
    """

    @type t :: %__MODULE__{
            text: binary(),
            offset: non_neg_integer(),
            block_id: Block.id() | nil,
            role: String.t() | nil,
            config_key: String.t() | nil
          }

    @enforce_keys [:text, :offset]
    defstruct [:text, :offset, :block_id, :role, :config_key]
  end

  defmodule Line do
    @moduledoc """
    One reader's line: the spans it holds, its 1-based number, and the
    nesting depth it is drawn at.
    """

    @type t :: %__MODULE__{
            number: pos_integer(),
            indent: non_neg_integer(),
            spans: [Span.t()]
          }

    @enforce_keys [:number]
    defstruct [:number, indent: 0, spans: []]
  end

  @typedoc """
  `:pending` - nothing has been compiled yet, which is the value a caller
  holds before it first asks. `:compile_error` - the document does not
  compile and there is no earlier listing to fall back on (normal mid-edit,
  not exceptional); `findings` carries why. `:ready` - `lines` is the
  compiled chart, and `stale?` says whether it is the current document's.
  """
  @type status :: :pending | :ready | :compile_error

  @type t :: %__MODULE__{
          status: status(),
          lines: [Line.t()],
          findings: [Finding.t()],
          stale?: boolean(),
          line_count: non_neg_integer()
        }

  defstruct status: :pending, lines: [], findings: [], stale?: false, line_count: 0

  @doc """
  Compiles `document` against `palette` and returns the listing.

  `opts`:

    * `:declare` - forwarded verbatim to `StatifierBlocks.Compiler.compile/3`
      as its own `:declare` option, the host's raw `{id, expr}` declaration
      list. Defaults to `[]`.
    * `:previous` - the value this call replaces. When the compile fails and
      the previous value was `:ready`, that listing comes back with `stale?`
      set rather than being thrown away - see the moduledoc.
  """
  @spec build(Document.t(), Palette.t(), keyword()) :: t()
  def build(%Document{} = document, %Palette{} = palette, opts \\ []) when is_list(opts) do
    case Compiler.compile(document, palette, declare: Keyword.get(opts, :declare, [])) do
      {:ok, %Compiled{scxml: scxml, provenance: provenance}} ->
        lines = lines(scxml, provenance)
        %__MODULE__{status: :ready, lines: lines, line_count: length(lines)}

      {:error, findings} ->
        stale(Keyword.get(opts, :previous), findings)
    end
  end

  @doc """
  Every span in `view` the block `block_id` owns, in document order.

  What the panel highlights, and the same question the drawer's markup asks
  per span - here as a function, so a caller that wants the answer without
  the markup has one.
  """
  @spec spans_of(t(), Block.id()) :: [Span.t()]
  def spans_of(%__MODULE__{lines: lines}, block_id) when is_binary(block_id) do
    for %Line{spans: spans} <- lines, %Span{block_id: ^block_id} = span <- spans, do: span
  end

  @spec stale(t() | nil, [Finding.t()]) :: t()
  defp stale(%__MODULE__{status: :ready} = previous, findings),
    do: %{previous | stale?: true, findings: findings}

  defp stale(_none, findings), do: %__MODULE__{status: :compile_error, findings: findings}

  @spec lines(binary(), Provenance.t()) :: [Line.t()]
  defp lines(scxml, provenance) do
    starts = line_starts(scxml)

    scxml
    |> cut_points(provenance, starts)
    |> Enum.chunk_every(2, 1, :discard)
    |> Enum.map(fn [from, to] -> span(scxml, provenance, from, to) end)
    |> group(MapSet.new(starts))
    |> Enum.map(&merge_spans/1)
    |> number()
  end

  # Every `<` in the output opens a tag, so every `<` opens a line. Offset 0
  # joins the list so bytes ahead of the first tag - which the serializer
  # does not currently emit - still land on a line rather than nowhere.
  @spec line_starts(binary()) :: [non_neg_integer()]
  defp line_starts(scxml) do
    scxml
    |> :binary.matches("<")
    |> Enum.map(&elem(&1, 0))
    |> then(&[0 | &1])
    |> Enum.uniq()
    |> Enum.sort()
  end

  # Every offset at which the innermost owner or the line can change. Between
  # two consecutive cut points both are constant, which is what makes one
  # `owner_at/2` call per interval the whole of the resolution.
  @spec cut_points(binary(), Provenance.t(), [non_neg_integer()]) :: [non_neg_integer()]
  defp cut_points(scxml, %Provenance{spans: spans}, starts) do
    size = byte_size(scxml)

    spans
    |> Enum.flat_map(fn {{from, to}, _owner} -> [from, to] end)
    |> Enum.concat([0, size | starts])
    |> Enum.filter(&(&1 >= 0 and &1 <= size))
    |> Enum.uniq()
    |> Enum.sort()
  end

  @spec span(binary(), Provenance.t(), non_neg_integer(), non_neg_integer()) :: Span.t()
  defp span(scxml, provenance, from, to) do
    owner =
      case Provenance.owner_at(provenance, from) do
        {:ok, owner} -> owner
        {:error, {:unmapped_offset, _offset}} -> %{block_id: nil, role: nil, config_key: nil}
      end

    %Span{
      text: binary_part(scxml, from, to - from),
      offset: from,
      block_id: owner.block_id,
      role: owner.role,
      config_key: owner.config_key
    }
  end

  # Spans into lines: a span whose offset is a line start opens the next one.
  @spec group([Span.t()], MapSet.t(non_neg_integer())) :: [[Span.t()]]
  defp group(spans, starts) do
    spans
    |> Enum.reduce([], fn
      span, [] ->
        [[span]]

      span, [current | rest] = all ->
        if line_start?(span, starts), do: [[span] | all], else: [[span | current] | rest]
    end)
    |> Enum.map(&Enum.reverse/1)
    |> Enum.reverse()
  end

  @spec line_start?(Span.t(), MapSet.t(non_neg_integer())) :: boolean()
  defp line_start?(%Span{offset: offset}, starts), do: MapSet.member?(starts, offset)

  # Adjacent runs with the same owner are one run: the cut points are the
  # union of two independent sets, so a span endpoint that coincides with
  # nothing interesting splits a run the reader would rather see whole. The
  # earliest offset survives, which is the offset the merged run starts at.
  @spec merge_spans([Span.t()]) :: [Span.t()]
  defp merge_spans(spans) do
    spans
    |> Enum.reduce([], fn
      span, [previous | rest]
      when previous.block_id == span.block_id and
             previous.role == span.role and
             previous.config_key == span.config_key ->
        [%{previous | text: previous.text <> span.text} | rest]

      span, acc ->
        [span | acc]
    end)
    |> Enum.reverse()
  end

  # The numbers and the nesting depth, in one pass, because the depth of a
  # line is a function of every line before it. A closing tag is drawn at
  # the depth it closes rather than one deeper; an empty-element tag opens
  # nothing.
  @spec number([[Span.t()]]) :: [Line.t()]
  defp number(grouped) do
    {lines, _depth} =
      grouped
      |> Enum.with_index(1)
      |> Enum.map_reduce(0, fn {spans, index}, depth ->
        text = Enum.map_join(spans, & &1.text)
        indent = if closing?(text), do: max(depth - 1, 0), else: depth

        {%Line{number: index, indent: indent, spans: spans}, next_depth(text, indent)}
      end)

    lines
  end

  @spec next_depth(binary(), non_neg_integer()) :: non_neg_integer()
  defp next_depth(text, indent) do
    if opening?(text), do: indent + 1, else: indent
  end

  @spec closing?(binary()) :: boolean()
  defp closing?(text), do: String.starts_with?(text, "</")

  @spec opening?(binary()) :: boolean()
  defp opening?(text) do
    String.starts_with?(text, "<") and not closing?(text) and
      not String.ends_with?(String.trim_trailing(text), "/>")
  end
end
